CREATE TABLE "logistics_gate_io" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"zone" varchar(255),
	"district" varchar(255),
	"destination" varchar(255),
	"doOrderDate" date,
	"doOrderTime" varchar(50),
	"gateInDate" date,
	"gateInTime" varchar(50),
	"processingTime" varchar(100),
	"wbInDate" date,
	"wbInTime" varchar(50),
	"diffGateInTareWt" varchar(100),
	"wbOutDate" date,
	"wbOutTime" varchar(50),
	"diffTareWtGrossWt" varchar(100),
	"gateOutDate" date,
	"gateOutTime" varchar(50),
	"diffGrossWtGateOut" varchar(100),
	"diffGrossWtInvoiceDT" varchar(100),
	"diffInvoiceDTGateOut" varchar(100),
	"diffGateInGateOut" varchar(100),
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
