ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_1" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_2" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_3" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_4" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_5" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_6" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_7" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_8" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_9" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_10" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_11" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_12" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_13" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_14" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_15" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_16" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_17" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_18" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_19" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_20" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_21" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_22" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_23" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_24" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_25" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_26" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_27" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_28" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_29" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_30" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "bestcement"."sales_reports" ADD COLUMN "day_31" numeric(10, 2);